### ISSUE TITLE
Add description to the hook

### ISSUE THREAD

**Issue by akramfstg** [Gamesight/slack-workflow-status#42]
We would like to have another field like **'description'** in the action to inject a link or an URL for reference:
```
- name: Slack Workflow Notification with Merged PR
  uses: Gamesight/slack-workflow-status@master
  with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK}}
          channel: 'XXX-test'
          name: Production deployment
          **description: PR linked https://github.com/XXX**
          icon_emoji: ':xxx:'
          include_jobs: true
          include_commit_message: true
```
Is that feasible?
Thanks
